# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ayxbzg5rJvy10LmnJVcpl8vFQX14rSmo
"""

!pip install beautifulsoup4

rules = """
Make the text clearer and more professional.
Keep the same language as the source text.
Do not translate.
Do not change names, links, dates, numbers, or technical terms.
Do not change existing facts, numbers, or dates.
Do not create new information.
Do not delete existing information.
Avoid compound sentences.
Use short and active statements.
Use B1 language level.
Use correct grammar and spelling.
Use inclusive language.
"""

html_text = """
<div class="document">
  <h1>Internal Process for Customer Request Handling</h1>

  <p>
    This document is written for employees that need to know what they must do when a customer request is coming in and it is important that the request is handled in the correct way because otherwise the customer can receive different answers from different teams.
  </p>

  <p>
    The process started on <strong>12 March 2024</strong> and it applies to all requests that are received after this date. The owner of the process is <span class="person-name">Mike Johnson</span>. Mike Johnson is responsible for making sure the process is followed by the teams.
  </p>

  <h2>Purpose of the process</h2>

  <p>
    The purpose of this process is that we want to make sure that every customer receives an answer that is clear, complete and sent at the right moment, and that the same information is not asked many times by different people in the company.
  </p>

  <p>
    Employees must use the <a href="https://example.com/customer-request-form">Customer Request Form</a> before they start working on the request. The form has <strong>7 required fields</strong>. These fields may not be skipped.
  </p>

  <h2>What employees must do</h2>

  <ul>
    <li>
      Read the full request before you send an answer, because sometimes the most important information is written at the end of the request.
    </li>
    <li>
      Check if the customer already has an open ticket.
      <ol>
        <li>
          Search by customer name, email address and contract number.
        </li>
        <li>
          If there is already an open ticket, add the new information to that ticket and do not create a second ticket.
        </li>
        <li>
          If there is no open ticket, create a new ticket and add the request date.
        </li>
      </ol>
    </li>
    <li>
      Make sure that the status is changed to <span class="status">In progress</span> when somebody starts working on the request.
    </li>
    <li>
      Do not close the request before the customer has received the final answer.
    </li>
  </ul>

  <h3>Important exception</h3>

  <p>
    If the request is about a payment problem, the employee must send the request to the Finance team within <strong>2 working days</strong>. This rule was approved on <span class="date">4 June 2024</span>.
  </p>

  <blockquote>
    Requests about invoices, payment delays and refund questions must always be checked carefully before an answer is sent to the customer.
  </blockquote>

  <h2>Information that must not be changed</h2>

  <p>
    The following information must stay exactly the same in every document and message: customer name, contract number, request date, payment amount and ticket number.
  </p>

  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th>Required action</th>
        <th>Deadline</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Customer name</td>
        <td>The name must be copied from the original request and it must not be shortened or changed.</td>
        <td>Same day</td>
      </tr>
      <tr>
        <td>Contract number</td>
        <td>The number must be checked in the system before the ticket is created.</td>
        <td>Same day</td>
      </tr>
      <tr>
        <td>Payment issue</td>
        <td>The issue must be sent to Finance when the amount is higher than €500.</td>
        <td>2 working days</td>
      </tr>
    </tbody>
  </table>

  <h2>Nested instructions</h2>

  <ul>
    <li>
      When the customer asks for an update, the employee must first check the current ticket status.
      <ul>
        <li>
          If the status is <strong>Waiting for customer</strong>, ask the customer for the missing information again.
        </li>
        <li>
          If the status is <strong>Waiting for internal team</strong>, contact the team owner.
          <ol>
            <li>
              Sent one reminder after <span>3 working dayss</span>.
            </li>
            <li>
              Send a second reminded after <span>5 working working days</span>.
            </li>
            <li>
              Escalate the ticket to <strong>Mike Johnson</strong> after <span>7 working days</span>.
            </li>
          </ol>
        </li>
      </ul>
    </li>
    <li>
      When the customer says that the answer is not clear, the employee must rewrite the answer and avoid long explanations that are difficult to understand.
    </li>
  </ul>

  <figure>
    <img src="customer-request-flow.png" alt="Customer request flow diagram">
    <figcaption>
      This image shows the customer request flow from the moment the request is received until the final answer is sent.
    </figcaption>
  </figure>

  <h2>Final check before closing</h2>

  <p>
    Before the ticket is closed, the employee must check if all required information is present, if the customer received the answer, if the ticket status is correct and if no duplicate ticket was created.
  </p>

  <p>
    The ticket may be closed only when the final answer was sent and the customer does not need to send more information. The closing note must include the date, the employee name and a short explanation of the answer that was sent.
  </p>
</div>
"""

def make_repeated_test_section(i: int) -> str:
    return f"""
  <section class="generated-process-section" data-section="{i}">
    <h2>Additional customer request scenario {i}</h2>

    <p>
      This section is added to make the test document longer and it describes a customer request situation where the employee must read the request carefully, because the customer may include important information in the last sentence and the employee should not answer before the full request is checked.
    </p>

    <p>
      The scenario started on <strong>{(i % 28) + 1} March 2024</strong> and it is owned by <span class="person-name">Mike Johnson</span>. Mike Johnson must make sure that the request is checked by the right team and that the answer is not sent too late.
    </p>

    <ul>
      <li>
        The employee must check if the customer already has an open ticket before a new ticket is created.
        <ol>
          <li>
            Search by customer name, email address and contract number.
          </li>
          <li>
            If a ticket already exists, add the new information to that ticket and do not create a duplicate ticket.
          </li>
          <li>
            If no ticket exists, create a new ticket and add the request date.
          </li>
        </ol>
      </li>
      <li>
        The status must be changed to <span class="status">In progress</span> when the work starts.
      </li>
      <li>
        The request must not be closed before the customer receives the final answer.
      </li>
    </ul>

    <p>
      Employees must use the <a href="https://example.com/customer-request-form">Customer Request Form</a> and they must fill in <strong>7 required fields</strong>. The fields may not be skipped, because missing information can cause delays for the customer and for the internal team.
    </p>

    <blockquote>
      Payment questions, refund questions and invoice questions must always be checked carefully before an answer is sent to the customer.
    </blockquote>

    <table>
      <thead>
        <tr>
          <th>Scenario field</th>
          <th>Required action</th>
          <th>Deadline</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Customer name</td>
          <td>The name must be copied exactly from the original request and it must not be changed.</td>
          <td>Same day</td>
        </tr>
        <tr>
          <td>Contract number</td>
          <td>The number must be checked in the system before the ticket is created.</td>
          <td>Same day</td>
        </tr>
        <tr>
          <td>Payment issue</td>
          <td>The issue must be sent to Finance when the amount is higher than €500.</td>
          <td>2 working days</td>
        </tr>
      </tbody>
    </table>

    <p>
      If the customer asks for an update, the employee must first check the current ticket status and the employee must not give an answer that is based on old information.
    </p>

    <ul>
      <li>
        If the status is <strong>Waiting for customer</strong>, ask the customer for the missing information again.
      </li>
      <li>
        If the status is <strong>Waiting for internal team</strong>, contact the team owner.
        <ol>
          <li>Send one reminder after <span>3 working dayss</span>.</li>
          <li>Send a second reminded after <span>5 working working days</span>.</li>
          <li>Escalate the ticket to <strong>Mike Johnson</strong> after <span>7 working days</span>.</li>
        </ol>
      </li>
    </ul>

    <p>
      Before the ticket is closed, the employee must check if all required information is present, if the customer received the answer, if the ticket status is correct and if no duplicate ticket was created.
    </p>
  </section>
"""


def make_html_exactly_target_chars(original_html: str, target_chars: int = 100_000) -> str:
    """
    Expands an existing HTML fragment to exactly target_chars characters.

    It inserts repeated realistic sections before the final </div>.
    Most added content is real editable text, not comments.
    """

    if not isinstance(original_html, str):
        raise TypeError("original_html must be a string.")

    if target_chars <= 0:
        raise ValueError("target_chars must be positive.")

    base = original_html.strip()

    closing_tag = "</div>"
    closing_index = base.rfind(closing_tag)

    if closing_index == -1:
        prefix = '<div class="document">\n' + base + "\n"
        suffix = "\n</div>"
    else:
        prefix = base[:closing_index].rstrip() + "\n"
        suffix = base[closing_index:]

    if len(prefix) + len(suffix) > target_chars:
        raise ValueError(
            f"Original HTML is already longer than target_chars. "
            f"Current minimum length is {len(prefix) + len(suffix)}."
        )

    sections = []
    current_len = len(prefix) + len(suffix)

    i = 1

    while True:
        section = make_repeated_test_section(i)
        remaining_after_section = target_chars - (current_len + len(section))

        # Leave room for a final filler paragraph if needed.
        if remaining_after_section == 0:
            sections.append(section)
            current_len += len(section)
            break

        if remaining_after_section > 120:
            sections.append(section)
            current_len += len(section)
            i += 1
            continue

        break

    remaining = target_chars - current_len

    if remaining > 0:
        filler_start = '\n  <p class="length-filler">'
        filler_end = '</p>\n'
        wrapper_len = len(filler_start) + len(filler_end)

        # If the remaining space is too small for a valid filler paragraph,
        # remove one generated section and use the larger remaining space.
        if remaining < wrapper_len:
            if not sections:
                raise ValueError("Not enough room to create valid filler paragraph.")

            removed = sections.pop()
            current_len -= len(removed)
            remaining = target_chars - current_len

        filler_text_len = remaining - wrapper_len

        filler_unit = (
            " This extra sentence is included to make the generated HTML longer. "
            "It gives the rewriting function more editable text to process. "
            "The employee must still keep facts, dates, names, links and numbers unchanged. "
        )

        filler_text = (filler_unit * ((filler_text_len // len(filler_unit)) + 2))[:filler_text_len]
        filler = filler_start + filler_text + filler_end

        sections.append(filler)
        current_len += len(filler)

    expanded_html = prefix + "".join(sections) + suffix

    assert len(expanded_html) == target_chars, len(expanded_html)

    return expanded_html

html_text = make_html_exactly_target_chars(html_text, target_chars=100_000)

print(len(html_text))
print(html_text[:1000])
print(html_text[-1000:])

from __future__ import annotations

from bs4 import BeautifulSoup, Tag, NavigableString, Comment, Doctype
from html import escape
import copy


VOID_TAGS = {
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}


def split_html_by_token_limit(
    html_text: str,
    max_tokens: int,
    *,
    model: str = "gpt-4o-mini",
    parser: str = "html.parser",
    count_tokens=None,
) -> list[str]:
    """
    Split an HTML document into self-contained HTML chunks.

    Each returned chunk:
    - is valid/balanced HTML
    - is <= max_tokens according to count_tokens()
    - may repeat parent wrapper tags when a split happens inside nested content

    Important:
    - Chunks are safe to send independently to an LLM.
    - Do not simply concatenate the chunks back together if parent tags were repeated.
      Use a join/merge strategy if you need exact reconstruction later.

    Parameters:
    - html_text: input HTML
    - max_tokens: maximum token count per chunk
    - model: tokenizer model name used by tiktoken if count_tokens is not provided
    - parser: BeautifulSoup parser
    - count_tokens: optional function: count_tokens(text: str) -> int
    """

    if max_tokens <= 0:
        raise ValueError("max_tokens must be greater than 0.")

    if count_tokens is None:
        count_tokens = _make_tiktoken_counter(model)

    soup = BeautifulSoup(html_text, parser)

    splitter = _HtmlTokenSplitter(
        max_tokens=max_tokens,
        count_tokens=count_tokens,
    )

    for node in list(soup.contents):
        splitter.visit(node)

    chunks = splitter.finish()

    # Final safety check.
    too_large = [
        (i, count_tokens(chunk))
        for i, chunk in enumerate(chunks)
        if count_tokens(chunk) > max_tokens
    ]

    if too_large:
        raise RuntimeError(
            f"Internal error: some chunks exceed max_tokens: {too_large[:5]}"
        )

    return chunks


def _make_tiktoken_counter(model: str):
    try:
        import tiktoken
    except ImportError as exc:
        raise ImportError(
            "Install tiktoken or pass your own count_tokens function:\n"
            "pip install tiktoken"
        ) from exc

    try:
        encoding = tiktoken.encoding_for_model(model)
    except KeyError:
        encoding = tiktoken.get_encoding("cl100k_base")

    def count_tokens(text: str) -> int:
        return len(encoding.encode(text))

    return count_tokens


class _HtmlTokenSplitter:
    def __init__(self, *, max_tokens: int, count_tokens):
        self.max_tokens = max_tokens
        self.count_tokens = count_tokens

        self.chunks: list[str] = []
        self.buffer: list[str] = []
        self.stack: list[Tag] = []

    def finish(self) -> list[str]:
        if self.buffer:
            html = self._current_self_contained_html()
            self._assert_fits(html)
            self.chunks.append(html)
            self.buffer = []

        return [chunk for chunk in self.chunks if chunk.strip()]

    def visit(self, node) -> None:
        if isinstance(node, Doctype):
            self._push_piece(f"<!DOCTYPE {node}>")
            return

        if isinstance(node, Comment):
            self._push_piece(f"<!--{node}-->")
            return

        if isinstance(node, NavigableString):
            self._push_text(str(node))
            return

        if isinstance(node, Tag):
            self._visit_tag(node)
            return

        self._push_piece(str(node))

    def _visit_tag(self, tag: Tag) -> None:
        tag_name = tag.name.lower()

        if tag_name in VOID_TAGS:
            self._push_piece(_open_tag_html(tag))
            return

        opening = _open_tag_html(tag)

        # Opening a tag increases the active stack, so test with the future stack.
        future_stack = self.stack + [tag]
        self._push_piece(opening, stack_for_fit=future_stack)
        self.stack.append(tag)

        for child in list(tag.contents):
            self.visit(child)

        # Closing a tag should fit because all previous fits reserved room for
        # currently open closing tags.
        closing = f"</{tag.name}>"
        self.buffer.append(closing)
        self.stack.pop()

    def _push_text(self, text: str) -> None:
        if not text:
            return

        remaining = text

        while remaining:
            escaped = escape(remaining, quote=False)

            if self._fits(escaped):
                self.buffer.append(escaped)
                return

            # If current buffer has content, flush first and try again.
            if self._has_real_buffer_content():
                self._flush_and_reopen_stack()
                continue

            # Buffer is empty except reopened wrappers, so split the text itself.
            prefix, suffix = self._split_text_to_fit(remaining)

            if not prefix:
                raise ValueError(
                    "Cannot split text to fit max_tokens. "
                    "The active HTML wrapper path may be too large."
                )

            self.buffer.append(escape(prefix, quote=False))
            remaining = suffix

            if remaining:
                self._flush_and_reopen_stack()

    def _push_piece(self, html_piece: str, *, stack_for_fit: list[Tag] | None = None) -> None:
        if not html_piece:
            return

        if self._fits(html_piece, stack_for_fit=stack_for_fit):
            self.buffer.append(html_piece)
            return

        if self._has_real_buffer_content():
            self._flush_and_reopen_stack()

        if self._fits(html_piece, stack_for_fit=stack_for_fit):
            self.buffer.append(html_piece)
            return

        raise ValueError(
            "A single HTML piece cannot fit inside max_tokens. "
            "Try increasing max_tokens or splitting large text earlier."
        )

    def _fits(self, html_piece: str, *, stack_for_fit: list[Tag] | None = None) -> bool:
        stack = self.stack if stack_for_fit is None else stack_for_fit
        candidate = "".join(self.buffer) + html_piece + _closing_tags_html(stack)
        return self.count_tokens(candidate) <= self.max_tokens

    def _current_self_contained_html(self) -> str:
        return "".join(self.buffer) + _closing_tags_html(self.stack)

    def _flush_and_reopen_stack(self) -> None:
        html = self._current_self_contained_html()
        self._assert_fits(html)

        if html.strip():
            self.chunks.append(html)

        self.buffer = []

        # Reopen active parent path in the next chunk so the fragment is self-contained.
        for tag in self.stack:
            self.buffer.append(_open_tag_html(tag))

        reopened = self._current_self_contained_html()
        if self.count_tokens(reopened) > self.max_tokens:
            raise ValueError(
                "The reopened parent tag stack alone exceeds max_tokens. "
                "Increase max_tokens or split at a higher-level boundary."
            )

    def _split_text_to_fit(self, text: str) -> tuple[str, str]:
        """
        Return (prefix_that_fits, remainder).
        Uses binary search, then prefers a whitespace/sentence boundary.
        """
        if not text:
            return "", ""

        low = 1
        high = len(text)
        best = 0

        while low <= high:
            mid = (low + high) // 2
            candidate = escape(text[:mid], quote=False)

            if self._fits(candidate):
                best = mid
                low = mid + 1
            else:
                high = mid - 1

        if best == 0:
            return "", text

        # Prefer a cleaner cut if possible.
        if best < len(text):
            window_start = max(0, int(best * 0.6))
            preferred_cuts = [
                text.rfind("\n\n", window_start, best),
                text.rfind("\n", window_start, best),
                text.rfind(". ", window_start, best),
                text.rfind("! ", window_start, best),
                text.rfind("? ", window_start, best),
                text.rfind("; ", window_start, best),
                text.rfind(", ", window_start, best),
                text.rfind(" ", window_start, best),
            ]

            cut = max(preferred_cuts)

            if cut > 0:
                # Include the separator when useful.
                if text[cut:cut + 2] in {". ", "! ", "? ", "; ", ", "}:
                    cut += 2
                elif text[cut:cut + 1] in {" ", "\n"}:
                    cut += 1

                if self._fits(escape(text[:cut], quote=False)):
                    best = cut

        return text[:best], text[best:]

    def _has_real_buffer_content(self) -> bool:
        """
        True if the buffer has more than just reopened parent wrappers.
        Simple practical check: any content exists beyond the active opening stack.
        """
        if not self.buffer:
            return False

        reopened_prefix = "".join(_open_tag_html(tag) for tag in self.stack)
        current = "".join(self.buffer)

        return current != reopened_prefix

    def _assert_fits(self, html: str) -> None:
        tokens = self.count_tokens(html)
        if tokens > self.max_tokens:
            raise ValueError(
                f"Chunk exceeds max_tokens: {tokens} > {self.max_tokens}"
            )


def _open_tag_html(tag: Tag) -> str:
    attrs = _attrs_to_html(tag.attrs)
    return f"<{tag.name}{attrs}>"


def _attrs_to_html(attrs: dict) -> str:
    parts = []

    for key, value in attrs.items():
        if value is None:
            continue

        if value is True:
            parts.append(key)
            continue

        if isinstance(value, list):
            value = " ".join(str(v) for v in value)

        escaped_value = escape(str(value), quote=True)
        parts.append(f'{key}="{escaped_value}"')

    if not parts:
        return ""

    return " " + " ".join(parts)


def _closing_tags_html(stack: list[Tag]) -> str:
    return "".join(f"</{tag.name}>" for tag in reversed(stack))

chunks = split_html_by_token_limit(
    html_text,
    max_tokens=8000,
    model="gpt-4o-mini",
)

count_tokens = _make_tiktoken_counter("gpt-4o-mini")

for i, chunk in enumerate(chunks, 1):
    print(i, count_tokens(chunk))

print(chunk[5])